export const EVENTS = [
  {
    id: 1,
    image:
      "https://media-cdn.tripadvisor.com/media/photo-s/1c/c7/44/e5/stand-up-comedy-night.jpg",
    title: "Stand-Up Comedy Night",
    date: "August 15th, 2024",
    text: "Get ready to laugh until your sides hurt with top comedians delivering hilarious stand-up routines.",
    location: "Laugh Factory, New York",
    category: "comedy",
    price: 120,
  },
  {
    id: 2,
    image:
      "https://media-cdn.tripadvisor.com/media/photo-s/1c/c7/44/e5/stand-up-comedy-night.jpg",
    title: "Comedy Improv Show",
    date: "September 5th, 2024",
    text: "Experience the spontaneity and wit of improv comedy with talented improvisers.",
    location: "Comedy Club, Chicago",
    category: "comedy",
    price: 150,
  },
  {
    id: 3,
    image: "https://shorturl.at/lJ157",
    title: "Summer Music Festival",
    date: "October 20th, 2024",
    text: "Jam out to your favorite bands and artists at this epic outdoor music festival.",
    location: "City Park, Los Angeles",
    category: "concert",
    price: 250,
  },
  {
    id: 4,
    image: "https://shorturl.at/lJ157",
    title: "Rock Concert",
    date: "November 10th, 2024",
    text: "Experience the energy of live music with electrifying performances by rock bands.",
    location: "Arena Stadium, San Francisco",
    category: "concert",
    price: 166,
  },
  {
    id: 5,
    image:
      "https://media-cdn.tripadvisor.com/media/photo-s/1c/c7/44/e5/stand-up-comedy-night.jpg",
    title: "Comedy Showcase",
    date: "December 3rd, 2024",
    text: "Discover new comedic talents and enjoy a night of laughter with up-and-coming comedians.",
    location: "Comedy Lounge, Miami",
    category: "comedy",
    price: 350,
  },
  {
    id: 6,
    image: "https://shorturl.at/lJ157",
    title: "Classical Music Concert",
    date: "January 15th, 2025",
    text: "Immerse yourself in the beauty of classical music performed by world-renowned musicians.",
    location: "Symphony Hall, Dallas",
    category: "concert",
    price: 410,
  },
  {
    id: 7,
    image:
      "https://media-cdn.tripadvisor.com/media/photo-s/1c/c7/44/e5/stand-up-comedy-night.jpg",
    title: "Comedy Special Event",
    date: "February 8th, 2025",
    text: "Prepare for a night of uproarious comedy with special guest appearances and surprises.",
    location: "Comedy Theater, Seattle",
    category: "comedy",
    price: 120,
  },
  {
    id: 8,
    image: "https://shorturl.at/lJ157",
    title: "Pop Music Concert",
    date: "March 22nd, 2025",
    text: "Dance the night away to chart-topping hits performed live by popular artists.",
    location: "Music Arena, Boston",
    category: "concert",
    price: 129,
  },
  {
    id: 9,
    image:
      "https://media-cdn.tripadvisor.com/media/photo-s/1c/c7/44/e5/stand-up-comedy-night.jpg",
    title: "Comedy Roast Battle",
    date: "April 18th, 2025",
    text: "Witness comedians go head-to-head in a hilarious battle of wits and insults.",
    location: "Roast Club, Paris",
    category: "comedy",
    price: 170,
  },
  {
    id: 10,
    image: "https://shorturl.at/lJ157",
    title: "Jazz Concert",
    date: "May 7th, 2025",
    text: "Soothe your soul with smooth jazz melodies performed by talented jazz musicians.",
    location: "Jazz Lounge, London",
    category: "concert",
    price: 20,
  },
  {
    id: 11,
    image:
      "https://media-cdn.tripadvisor.com/media/photo-s/1c/c7/44/e5/stand-up-comedy-night.jpg",
    title: "Comedy Open Mic Night",
    date: "June 12th, 2025",
    text: "Experience the raw talent of aspiring comedians as they take the stage for an open mic night.",
    location: "Funny Bone Comedy Club, Denver",
    category: "comedy",
    price: 90,
  },
  {
    id: 12,
    image: "https://shorturl.at/lJ157",
    title: "Indie Music Concert",
    date: "July 8th, 2025",
    text: "Discover emerging indie bands and enjoy an intimate concert experience.",
    location: "Small Venue, Portland",
    category: "concert",
    price: 80,
  },
  {
    id: 13,
    image:
      "https://media-cdn.tripadvisor.com/media/photo-s/1c/c7/44/e5/stand-up-comedy-night.jpg",
    title: "Comedy Film Screening",
    date: "August 21st, 2025",
    text: "Laugh out loud at a screening of classic comedy films from the golden era of cinema.",
    location: "Cineplex, Vancouver",
    category: "comedy",
    price: 85,
  },
  {
    id: 14,
    image: "https://shorturl.at/lJ157",
    title: "Acoustic Music Night",
    date: "September 19th, 2025",
    text: "Enjoy the intimate atmosphere of acoustic music performances by talented musicians.",
    location: "Coffee House, Seattle",
    category: "concert",
    price: 190,
  },
  {
    id: 15,
    image:
      "https://media-cdn.tripadvisor.com/media/photo-s/1c/c7/44/e5/stand-up-comedy-night.jpg",
    title: "Comedy Workshop",
    date: "October 12th, 2025",
    text: "Learn the art of comedy with hands-on workshops and coaching from experienced comedians.",
    location: "Comedy Academy, Los Angeles",
    category: "comedy",
    price: 120,
  },
  {
    id: 16,
    image: "https://shorturl.at/lJ157",
    title: "Electronic Dance Music Festival",
    date: "November 7th, 2025",
    text: "Experience the ultimate EDM festival with pulsating beats and electrifying performances.",
    location: "Rave Park, Miami",
    category: "concert",
    price: 124,
  },
  {
    id: 17,
    image:
      "https://img.freepik.com/free-photo/excited-audience-watching-confetti-fireworks-having-fun-music-festival-night-copy-space_637285-559.jpg?w=740&t=st=1687771518~exp=1687772118~hmac=4a7290acfe18ad1949e0b2c8802193c287288b245eb6020c5140df6b8246fc98",
    title: "Rage Against The Machine",
    date: "May 6th, 2024",
    text: "Get ready to experience the raw energy and rebellious spirit of one of the most iconic bands of all time! Rage Against the Machine is back with their explosive live performance that will shake the foundations of the Revolution Arena in Los Angeles.",
    location: "Main Park, Los Angeles",
    category: "concert",
    price: 500,
  },
];
